roles:
  - name: docker
    scm: git
    src: https://github.com/sasha-shs/docker.git
    version: main
    
  - name: nginx
    scm: git
    src: https://github.com/sasha-shs/nginx.git
    version: main

# ansible-galaxy install -r requirements.yml